application: wiltongarcia-1236
version: 1
runtime: php55
api_version: 1

handlers:
- url: /assets
  static_dir: public/assets

- url: /.*
  script: public/index.php

- url: /favicon\.ico
  static_files: public/favicon.ico
  upload: favicon\.ico
